#!/bin/bash
local=`echo $PWD | rev | cut -d'/' -f 1 | rev`
directory=$local
git clone https://github.com/edumast/term_py
mv ~/$directory/term_py/update/* ~/$directory/update
mv ~/$directory/term_py/* ~/$directory
rm -rf term_py
